### ISSUE TITLE
Tag for stable for Silex 2

### ISSUE THREAD

**Issue by SpacePossum** [nrk/PredisServiceProvider#17]
Hi,

I was wondering if you are planning on creating a release branch/tag with a stable version for Silex 2?
Master seems stable ATM for usage with Silex 2/Pimple, but I would like to set my projects composer config on release rather than master.

**Comment by Toflar** [comment]
Same here :)

**Comment by nrk** [comment]
Sorry for being so inactive on this project, I'll try to make up for it soon :smile: As for a new branch and release targeting Silex 2... yes it's going to happen, I just have a doubt if the `Predis\Silex` namespace should remain as is or if we could rename it as  `Predis\Pimple`, this service provider doesn't really depend on Silex anymore after all. Any thoughts on this?

**Comment by Toflar** [comment]
No worries. I just figured the master branch is working fine for me so why not tag it :) I'm fine with changing the namespace to `I'm fine with `Pimple` too, makes sense.

**Comment by SpacePossum** [comment]
I've no strong opinion on the move to another namespace. 
For example the Silex providers have been made independent of the Silex Application and rely on Pimple only, yet they are still in the Silex namespace (for example https://github.com/silexphp/Silex-Providers/blob/master/AssetServiceProvider.php).

If you make the move it would be nice to keep the current classes (although empty but their constructor) and let those extend the new ones in the new namespace and add deprecation notifications in the constructors. That way people who now use the master branch will be warned that the classes are moved to another namespace and can update their code. Than on 2.x you can drop the deprecated classes.

**Comment by nrk** [comment]
Tagged with no changes for the namespace of this provider.

**Comment by Toflar** [comment]
Thank you @nrk !
